---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: events
  label: Events
  create: all
  match: "*"
- type: directory
  path: theatres
  label: Theatres
  create: all
  match: "*"
- type: directory
  path: archive
  label: Archive
  create: all
  match: "*"
upload_dir: public/images/uploads
public_path: "/images/uploads"
front_matter_path: "../uploads"
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
